name: remainder
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  rxdart:
  provider:
  shared_preferences:
  flutter_local_notifications:
  flare_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/sound/

  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/ic/ic_medicine.ttf
    - family: Angel
      fonts:
        - asset: assets/fonts/neu/Angel Signature.ttf